### ISSUE TITLE
Windows Only tag is inconsistent with the rest of the documentation.

### ISSUE THREAD

**Issue by WalkQuackBack** [TKMM-Team/Tkmm-Wiki#8]
https://tkmm.org/docs/settings/#show-console

The Windows Only info card is inconsistent with the rest of the documentation.

It is in a blockquote, which misrepresents what it is, and the italicing and the star do not help with understanding what it means. Typically, a star/astrisk represents a field is required. However, enabling the Show Console option is not required which is confusing.

The text is seemingly italiced for no reason: if it is supposed to draw emphasis, another presentation method such as an info box like this should be used:

> [!NOTE]
> This option is only available on Windows. You can view the log on other platforms by starting TKMM from the console.

**Comment by ArchLeaders** [comment]
The settings page is no longer in use, it will be completely rewritten.
